# Generated by Django 2.1.1 on 2018-09-15 18:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('twengage', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='follow_accounts',
            field=models.TextField(blank=True, default=None, max_length=3000, null=True, verbose_name='Twitter Accounts to Follow'),
        ),
        migrations.AlterField(
            model_name='account',
            name='hashtags',
            field=models.TextField(blank=True, default=None, max_length=3000, null=True, verbose_name='Twitter Hashtags'),
        ),
    ]
