# Generated by Django 2.1.1 on 2018-09-15 18:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('twengage', '0002_auto_20180916_0022'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='cookies',
            field=models.BinaryField(blank=True, default=None, null=True, verbose_name='Twitter Account Cookies'),
        ),
    ]
