# Generated by Django 2.1.1 on 2018-09-15 19:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('twengage', '0003_account_cookies'),
    ]

    operations = [
        migrations.RenameField(
            model_name='account',
            old_name='active',
            new_name='user_active',
        ),
        migrations.RenameField(
            model_name='account',
            old_name='verified',
            new_name='user_verified',
        ),
        migrations.AlterField(
            model_name='account',
            name='cookies',
            field=models.CharField(blank=True, default=None, max_length=2000, null=True, verbose_name='Twitter Account Cookies'),
        ),
    ]
