# Generated by Django 2.1.1 on 2018-09-15 19:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('twengage', '0004_auto_20180916_0041'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='current_following_account',
            field=models.TextField(blank=True, default=None, max_length=200, null=True, verbose_name='Working on this user'),
        ),
        migrations.AddField(
            model_name='account',
            name='current_hashtag',
            field=models.TextField(blank=True, default=None, max_length=200, null=True, verbose_name='Working on this tag'),
        ),
    ]
