# Generated by Django 2.1.1 on 2018-09-16 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('twengage', '0006_stat_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='notes',
            field=models.TextField(blank=True, default=None, max_length=3000, null=True, verbose_name='Notes'),
        ),
    ]
